# Numpy

Numpy is a library for representing and working with large and multi-dimensional arrays. Most other libraries in the data-science ecosystem depend on numpy, making it one of the fundamental data science libraries.

Numpy provides a number of useful tools for scientific programming, and in this lesson, we'll take a look at some of the most common.

Convention is to import the `numpy` module as `np`.

In [1]:
import numpy as np

## Indexing

Numpy provides an array type that goes above and beyond what Python's built-in lists can do.

We can create a numpy array by passing a list to the `np.array` function:

In [2]:
a = np.array([1, 2, 3])

In [3]:
a

array([1, 2, 3])

In [4]:
print(a)

[1 2 3]


We can create a multi-dimensional array by passing a list of lists to the `array` function

In [5]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [6]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Referencing elements in numpy arrays at it's most basic is the same as referencing elements in Python lists.

In [8]:
a[0]

1

In [9]:
print(a)

[1 2 3]


In [10]:
print('a    == {}'.format(a))
print('a[0] == {}'.format(a[0]))
print('a[1] == {}'.format(a[1]))
print('a[2] == {}'.format(a[2]))

a    == [1 2 3]
a[0] == 1
a[1] == 2
a[2] == 3


In [11]:
print('matrix')
print(matrix)
print('\n')
print('matrix[0] == {}'.format(matrix[0]))
print('matrix[1] == {}'.format(matrix[1]))
print('matrix[2] == {}'.format(matrix[2]))

matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]


matrix[0] == [1 2 3]
matrix[1] == [4 5 6]
matrix[2] == [7 8 9]


Multidimensional numpy arrays are easier to index into than nested lists. To obtain the element at the second column in the second row, we would write:

In [12]:
matrix[1,1]

5

To get the first 2 elements of the last 2 rows:

In [13]:
matrix[1:, :2] 
# 1: Give me the rows starting from index position 1 onward
# :2 Give me the elements of the rows up to but not including index position 2

array([[4, 5],
       [7, 8]])

Arrays can also be indexed with a boolean sequence used to indicate which values should be included in the resulting array.

In [14]:
a

array([1, 2, 3])

In [15]:
a[[True, False, True]]

array([1, 3])

In [16]:
should_include_elements_a = [True, False, True]
a[should_include_elements_a]

array([1, 3])

## Vectorized Operations

Another useful feature of numpy arrays is vectorized operations.

If we wanted to add 1 to every element in a list, without numpy, we can't simply add 1 to the list, as that will result in a `TypeError`.

In [17]:
original_array = [1, 2, 3, 4, 5]
try:
    original_array + 1
except TypeError as e:
    print('An Error Occured!')
    print(f'TypeError: {e}')

An Error Occured!
TypeError: can only concatenate list (not "int") to list


In [18]:
# What does "can only concatenate list (not "int") to list" mean?
[1, 2, 3, 4, 5] + [1]

[1, 2, 3, 4, 5, 1]

We could write a `for` loop or a list comprehension:

In [19]:
original_array = [1, 2, 3, 4, 5]
array_with_one_added = []
for n in original_array:
    array_with_one_added.append(n+1)
print(array_with_one_added)

[2, 3, 4, 5, 6]


In [20]:
original_array = [1, 2, 3, 4, 5]
array_with_one_added = [n + 1 for n in original_array]
print(array_with_one_added)

[2, 3, 4, 5, 6]


Vectorizing operations means that operations are automatically applied to every element in a vector, which in our case will be a numpy array. So if we are working with a numpy array, we can simply add 1:

In [21]:
numpy_array = np.array([1, 2, 3, 4, 5])
numpy_array + 1

array([2, 3, 4, 5, 6])

In [22]:
print(numpy_array + 2)

[3 4 5 6 7]


This works the same way for the other basic arithmetic operators as well:

In [23]:
my_array = np.array([-3, 0, 3, 16])

print(f'my_array      == {my_array}')
print(f'my_array - 5  == {my_array - 5}')
print(f'my_array * 4  == {my_array * 4}')
print(f'my_array / 2  == {my_array / 2}')
print(f'my_array ** 2 == {my_array ** 2}')
print(f'my_array % 2  == {my_array % 2}')

my_array      == [-3  0  3 16]
my_array - 5  == [-8 -5 -2 11]
my_array * 4  == [-12   0  12  64]
my_array / 2  == [-1.5  0.   1.5  8. ]
my_array ** 2 == [  9   0   9 256]
my_array % 2  == [1 0 1 0]


Not only are the arithmatic operators vectorized, but the same applies to the comparison operators.

In [24]:
my_array = np.array([-3, 0, 3, 16])

print(f'my_array       == {my_array}')
print(f'my_array == -3 == {my_array == -3}')
print(f'my_array >= 0  == {my_array >= 0}')
print(f'my_array < 10  == {my_array < 10}')

my_array       == [-3  0  3 16]
my_array == -3 == [ True False False False]
my_array >= 0  == [False  True  True  True]
my_array < 10  == [ True  True  True False]


If vectorizing a comparison operator produces a boolean array...

In [25]:
my_array

array([-3,  0,  3, 16])

In [26]:
print(my_array > 0)

[False False  True  True]


And if we can give an array some booleans to select the values we want to return...

In [27]:
my_array[[False, False, True, True]]

array([ 3, 16])

Then we can "give" an array a condition to select our values for us!

In [28]:
# Give me all the positive numbers in my_array:
my_array[my_array > 0]

array([ 3, 16])

## In-Depth Example
As another example, we could obtain all the even numbers like this:

In [29]:
my_array[my_array % 2 == 0]

array([ 0, 16])

To better understand how this is all working let's go through this recent example in a little more detail.

The first expression that gets evaluated is this:

In [30]:
my_array

array([-3,  0,  3, 16])

In [31]:
my_array % 2

array([1, 0, 1, 0])

Which results in an array of `1`s and `0`s. Then the array of `1`s and `0`s is compared to `0` with the `==` operator, producing an array of `True` or `False` values.

In [32]:
# Each element of the array % 2
result = my_array % 2
print(f"My Array:              {my_array}")
print(f"My Array % 2 (Result): {result}")

My Array:              [-3  0  3 16]
My Array % 2 (Result): [1 0 1 0]


In [33]:
# Does each element % 2 == 0?
print(f"My Array:                   {my_array}")
print(f"My Array % 2 (Result):      {result}")
print(f"result == 0:                {result == 0}")

My Array:                   [-3  0  3 16]
My Array % 2 (Result):      [1 0 1 0]
result == 0:                [False  True False  True]


Lastly, we use this array of boolean values to index into the original array, which gives us only the values that are evenly divisible by 2.

In [34]:
step_1 = my_array % 2
step_2 = (step_1 == 0)
step_3 = my_array[step_2]

step_3

array([ 0, 16])

Put another way, here is how the expression is evaluated:

In [35]:
print('1. my_array[my_array % 2 == 0]')
print('    - the original expression')
print('2. my_array[{} % 2 == 0]'.format(my_array))
print('    - variable substitution')
print('3. my_array[{} == 0]'.format(my_array % 2))
print('    - result of performing the vectorized modulus 2')
print('4. my_array[{}]'.format(my_array % 2 == 0))
print('    - result of comparing to 0')
print('5. {}[{}]'.format(my_array, my_array % 2 == 0))
print('    - variable substitution')
print('6. {}'.format(my_array[my_array % 2 == 0]))
print('    - our final result')

1. my_array[my_array % 2 == 0]
    - the original expression
2. my_array[[-3  0  3 16] % 2 == 0]
    - variable substitution
3. my_array[[1 0 1 0] == 0]
    - result of performing the vectorized modulus 2
4. my_array[[False  True False  True]]
    - result of comparing to 0
5. [-3  0  3 16][[False  True False  True]]
    - variable substitution
6. [ 0 16]
    - our final result


In [36]:
my_array

array([-3,  0,  3, 16])

In [37]:
# I want to find element >= 0 AND element < 10
my_array[(my_array >= 0) & (my_array < 10)]

array([0, 3])

In [38]:
my_array[(my_array < 0) | (my_array > 3)]

array([-3, 16])

In [39]:
len(my_array)

4

In [40]:
my_array[[True, False]] # Error occurs because boolean list is not same length as original array

IndexError: boolean index did not match indexed array along dimension 0; dimension is 4 but corresponding boolean dimension is 2

## Array Creation

Numpy provides several methods for creating arrays, we'll take a look at several of them.

### `np.random.randn`

`np.random.randn` can be used to create an array of specified length of random numbers drawn from the standard normal distribution.

> **Standard Normal Distribution**: Values range from -∞ to ∞ with equal distribution in both positive and negative direction, the mean is equal to 0, and the standard deviation is 1. The values represent z-scores, which are the number of standard deviations that point is from the mean.

In [41]:
np.random.randn(10)

array([-0.38382333, -1.74848816, -0.95333844, -0.10829398,  1.1823556 ,
       -0.91560879,  0.2050087 ,  0.58274794,  0.11916496, -1.56298842])

We can also pass a second argument to this function to define the shape of a two dimensional array.

In [42]:
np.random.randn(3, 4) # rows, columns

array([[-1.89088986, -1.21771479, -0.77885474,  0.71357526],
       [-2.02400743,  0.71135375, -1.54974879, -1.04912878],
       [-0.84583534,  0.12136922, -1.84710557, -0.93083984]])

If we wish to obtain original values from the z-scores of a normal distribution, we'll need to apply some arithmetic. 

To convert, we'll need to multiply by the standard deviation (*σ*) and add the mean (*μ*).

In [43]:
z_scores_iq = np.random.randn(20)
z_scores_iq

array([ 2.50769084,  0.15101937, -3.11176624, -0.06994918, -2.15571051,
       -0.06979169, -0.32953279,  0.17088534,  1.13948134, -0.09676998,
        0.85135822, -1.64034753,  0.48668401,  0.69940669, -1.00623168,
       -1.05429379, -0.57196509, -1.64520387,  0.93123079, -0.12617914])

In [44]:
μ = 100 # If we have a mean of 100...
σ = 15 # ...and a standard deviation of 15...

raw_iq_scores = σ * z_scores_iq + μ # We can derive the unscaled values
raw_iq_scores

array([137.61536267, 102.26529058,  53.32350646,  98.95076224,
        67.66434237,  98.9531246 ,  95.05700819, 102.56328003,
       117.09222005,  98.54845034, 112.77037336,  75.39478698,
       107.30026011, 110.49110041,  84.9065248 ,  84.18559319,
        91.4205237 ,  75.32194199, 113.9684619 ,  98.10731286])

### `np.zeros`, `np.ones`, `np.full`

The `zeros` function provides the ability to create an array of a specified size full of `0`s: 

In [45]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

The `ones` function does the same thing, but full of `1`s instead:

In [46]:
np.ones(5)

array([1., 1., 1., 1., 1.])

The `full` function allows you to specific a value:

In [47]:
np.full(3, 17)

array([17, 17, 17])

We can also use these methods to create multi-dimensional arrays by passing a tuple of the dimensions of the desired array, instead of a single integer value.

In [48]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
np.full((3, 4), 'hello')

array([['hello', 'hello', 'hello', 'hello'],
       ['hello', 'hello', 'hello', 'hello'],
       ['hello', 'hello', 'hello', 'hello']], dtype='<U5')

### `np.arange`

Numpy's `arange` function is very similar to python's built-in `range` function. It can take a single argument and generate a range from zero up to, but not including, the passed number.

In [51]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

We can also specify a starting point for the range:

In [52]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

As well as a step:

In [53]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

Unlike python's builtin `range`, numpy's `arange` can handle decimal numbers

In [54]:
np.arange(3, 5, 0.5)

array([3. , 3.5, 4. , 4.5])

### `np.linspace`

The `linspace` method creates a range of numbers between a minimum and a maximum, with a set number of elements.

In [55]:
# min: 1, max: 10, length: 4
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [56]:
# min: 1, max: 10, length: 7
np.linspace(1, 10, 7)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

> Note: Here the maximum is **inclusive**
## Array Methods

Numpy arrays also come with built-in methods to make many mathematical operations easier.

Some of the most common are:

### `.min`

In [57]:
a = np.array([1, 2, 3, 4, 5])

In [58]:
a.min()

1

### `.max`

In [59]:
a.max()

5

### `.mean`

In [60]:
a.mean()

3.0

### `.sum`

In [61]:
a.sum()

15

### `.std()`

In [62]:
a.std()

1.4142135623730951

# Exercises!

In your numpy-pandas-visualization-exercises repo, create a file named `numpy_exercises.py` for this exercise.

Use the following code for the questions below:

In [77]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

1. How many negative numbers are there?

In [66]:
a<0

array([False, False, False, False,  True,  True, False, False, False,
        True, False,  True])

In [64]:
a[a<0]

array([-2, -1, -6, -7])

In [65]:
a[a<0].size

4

2. How many positive numbers are there?

In [67]:
a[a>0]

array([ 4, 10, 12, 23,  3])

In [68]:
a[a>0].size

5

3. How many even positive numbers are there?

In [69]:
a[(a % 2 == 0) & (a > 0)]

array([ 4, 10, 12])

In [70]:
a[(a % 2 == 0) & (a > 0)].size

3

4. If you were to add 3 to each data point, how many positive numbers would there be?

In [78]:
add_three = a + 3

In [79]:
add_three

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [80]:
# The output does not reassign the value associated with the variable name add_three
add_three[add_three > 0]

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3,  6])

In [81]:
add_three

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [82]:
add_three[add_three > 0].size

10

In [83]:
add_three.size

12

###  `.size` vs. `.shape` vs. `len`

In [73]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(".size returns the total number of elements in the array, regardless of any nesting")
x.size

.size returns the total number of elements in the array, regardless of any nesting


6

In [74]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
print(".shape returns the dimensions of the array")
x.shape

.shape returns the dimensions of the array


(2, 3)

In [76]:
print("The Python len function returns the number of elements contained only in the outer-most array")
len(x)

The Python len function returns the number of elements contained only in the outer-most array


2

#### Continuing exercises...

5. If you squared each number, what would the new mean and standard deviation be?

In [84]:
squared = a ** 2
print(f"Mean: {squared.mean()}")
print(f"Standard Deviation: {squared.std()}")

Mean: 74.0
Standard Deviation: 144.0243035046516


6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See [this link](https://www.theanalysisfactor.com/centering-and-standardizing-predictors/) for more on centering.

In [85]:
centered = a - a.mean()
centered

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [86]:
centered.mean()

0.0

7. Calculate the z-score for each data point. 

In [91]:
zscores = (a - a.mean()) / a.std()
zscores

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

8. Copy the setup and exercise directions from [More Numpy Practice](https://gist.github.com/ryanorsinger/c4cf5a64ec33c014ff2e56951bc8a42d) into your `numpy_exercises.py` and add your solutions.

In [92]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

sum_of_a = sum(a)
sum_of_a

55

In [93]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = min(a)
min_of_a

1

In [94]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = max(a)
max_of_a

10

In [95]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = sum(a) / len(a)
mean_of_a

5.5

In [96]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
product_of_a = 1
for n in a:
    product_of_a = product_of_a * n

product_of_a

3628800

In [97]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = [n ** 2 for n in a]
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [98]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a = [n for n in a if n % 2 != 0]
odds_in_a

[1, 3, 5, 7, 9]

In [99]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = [n for n in a if n % 2 == 0]
evens_in_a

[2, 4, 6, 8, 10]

In [100]:
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

# base python approach to sum
# sum(b) throws an error since we have a list of lists

In [101]:
sum(b)

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [102]:
# we could do two loops.. or we could flatten the list of lists into one list
flattened_list = []
for numbers in b:
    for n in numbers:
        flattened_list.append(n)
flattened_list

[3, 4, 5, 6, 7, 8]

In [103]:
output = {
    "sum": sum(flattened_list),
    "min": min(flattened_list),
    "max": max(flattened_list),
    "avg": sum(flattened_list) / len(flattened_list),
    "squares": [n**2 for n in flattened_list]
}
output

{'sum': 33, 'min': 3, 'max': 8, 'avg': 5.5, 'squares': [9, 16, 25, 36, 49, 64]}

In [104]:
product = 1
for n in flattened_list:
    product *= n

output["product"] = product
output

{'sum': 33,
 'min': 3,
 'max': 8,
 'avg': 5.5,
 'squares': [9, 16, 25, 36, 49, 64],
 'product': 20160}

In [105]:
# Let's do things the numpy way!
b = [
    [3, 4, 5],
    [6, 7, 8]
]

b = np.array(b)
b

array([[3, 4, 5],
       [6, 7, 8]])

In [113]:
# Exercises 1, 2, 3, 4, 5, 7, 8
numpy_way = {
    "Exercise 1 - sum": b.sum(),
    "Exercise 2 - min": b.min(),
    "Exercise 3 - max": b.max(),
    "Exercise 4 - mean": b.mean(),
    "Exercise 5 - product": b.prod(),
    "Exercise 6 - list of squares": b**2,
    "Exercise 7 - odds only": b[b % 2 == 1],
    "Exercise 8 - evens only": b[b % 2 == 0]
}
numpy_way

{'Exercise 1 - sum': 33,
 'Exercise 2 - min': 3,
 'Exercise 3 - max': 8,
 'Exercise 4 - mean': 5.5,
 'Exercise 5 - product': 20160,
 'Exercise 6 - list of squares': array([[ 9, 16, 25],
        [36, 49, 64]]),
 'Exercise 7 - odds only': array([3, 5, 7]),
 'Exercise 8 - evens only': array([4, 6, 8])}

In [110]:
# Exercise 9 - print out the shape of the array b.
b.shape

(2, 3)

In [115]:
# Original b
b

array([[3, 4, 5],
       [6, 7, 8]])

In [114]:
# Exercise 10 - transpose the array b.
b.T

array([[3, 6],
       [4, 7],
       [5, 8]])

In [116]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
b.flatten()

array([3, 4, 5, 6, 7, 8])

In [117]:
# reshape the array b to be a single list of 6 numbers. (1 x 6)
b.reshape(1, 6)

array([[3, 4, 5, 6, 7, 8]])

In [118]:
# alternatively, we could create a list of 6 lists, each containing a single number
b.reshape(6, 1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [119]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

c = np.array(c)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [120]:
# Exercise 1 - Find the min, max, sum, and product of c.
{
    "sum": c.sum(),
    "min": c.min(),
    "max": c.max(),
    "mean": c.mean(),
    "product": c.prod()
}

{'sum': 45, 'min': 1, 'max': 9, 'mean': 5.0, 'product': 362880}

In [121]:
# Exercise 2 - Determine the standard deviation of c.
c.std()

2.581988897471611

In [122]:
# Exercise 3 - Determine the variance of c.
c.var()

6.666666666666667

In [123]:
# Exercise 4 - Print out the shape of the array c
c.shape

(3, 3)

In [128]:
# Exercise 5 - Transpose c and print out transposed result.
np.transpose(c)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [131]:
c.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [132]:
# Exercise 6 - Get the dot product of the array c with c. 
np.dot(c, c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

### Dot Product Explained

Result: Sum of the products of the elements at corresponding indices

Algorithm: multiply values at each corresponding index, then take the sum of that output

`a = [1, 2, 3]`

`b = [0, 1, 2]`

`[1*0, 2*1, 3*2]`

`[0, 2, 6]`

`sum([0, 2, 6])`

`8`

In [133]:
# Practical example of a dot product is a weighted average
# [attendance, exercises, projects, quiz]
weights = [.1, .2, .4, .3]

# actual grades for someone
grades = [100, 99, 72, 80]

weights = np.array(weights)
grades = np.array(grades)

np.dot(grades, weights)

82.6

In [134]:
grades.mean()

87.75

#### Continuing exercises...

In [135]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
c * c.T

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

In [136]:
(c * c.T).sum()

261

In [139]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
(c * c.T).prod()

131681894400

In [140]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

d = np.array(d)

In [141]:
# Exercise 1 - Find the sine of all the numbers in d
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [142]:
# Exercise 2 - Find the cosine of all the numbers in d
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [143]:
# Exercise 3 - Find the tangent of all the numbers in d
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [144]:
# Exercise 4 - Find all the negative numbers in d
d[d < 0]

array([-90, -30, -45, -45])

In [145]:
# Exercise 5 - Find all the positive numbers in d
d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [146]:
# Exercise 6 - Return an array of only the unique numbers in d.
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [147]:
# Exercise 7 - Determine how many unique numbers there are in d.
np.unique(d).size

11

In [148]:
# Exercise 8 - Print out the shape of d.
d.shape

(3, 6)

In [149]:
# Exercise 9 - Transpose and then print out the shape of d.
d.T.shape

(6, 3)

In [152]:
# Exercise 10 - Reshape d into an array of 9 x 2
d.reshape(9, 2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])

**Awesome Bonus** For much more practice with numpy, Go to https://github.com/rougier/numpy-100 and clone the repo down to your laptop. To clone a repository: - Copy the SSH address of the repository - cd ~/codeup-data-science - Then type `git clone git@github.com:rougier/numpy-100.git` - Now do `cd numpy-100` on your terminal. - Type `git remote remove origin`, so you won't accidentally try to push your work to Rougier's repo.

Congratulations! You have cloned Rougier's 100 numpy exercises to your computer. Now you need to make a new, blank, repository on GitHub.

Go to https://github.com/new to make a new repo. Name it numpy-100.
DO NOT check any check boxes. We need a blank, empty repo.
Finally, follow the directions to "push an existing repository from the command line" so that you can push up your changes to your own account.

Now do work, add it, commit it, and push it!